services:
  leader:
    build:
      context: ./leader
    image: 147063123581.dkr.ecr.us-west-1.amazonaws.com/leader:tony
    ports:
      - "8080:8080"
 #  volumes:
 #    - "~/.aws/:/root/.aws/"
    x-aws-policies:
      - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
    environment:
      ARCHIVO_PALABRAS: "medium_file"

  worker:
    build:
      context: ./worker
    image: 147063123581.dkr.ecr.us-west-1.amazonaws.com/follower:tony
    deploy:
      replicas: 4
    depends_on:
      - leader
 #  volumes:
 #    - "~/.aws/:/root/.aws/"
    x-aws-policies:
      - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
    environment:
      ARCHIVO_PALABRAS: "medium_file"
