services:
  leader:
    build:
      context: ./leader
    image: leader-csharp
    ports:
      - "8080:8080"
  worker:
    build:
      context: ./worker
    image: worker-csharp
    depends_on:
      - leader
